/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_se7en_update_BsdiffJNI */

#ifndef _Included_com_se7en_update_BsdiffJNI
#define _Included_com_se7en_update_BsdiffJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_douyu_im_bs_BsdiffJNI
 * Method:    applyPatchToOldApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_se7en_update_BsdiffJNI_applyPatchToOldApk
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
